#pragma once

#include <GL/gl.h>

namespace wwidget {

struct GL {
	PFNGLGETSTRINGIPROC               glGetStringi;
	PFNGLBINDBUFFERPROC               glBindBuffer;
	PFNGLGENBUFFERSPROC               glGenBuffers;
	PFNGLDELETEBUFFERSPROC            glDeleteBuffers;
	PFNGLBUFFERDATAPROC               glBufferData;
	PFNGLBUFFERSUBDATAPROC            glBufferSubData;
	PFNGLGETBUFFERSUBDATAPROC         glGetBufferSubData;
	PFNGLNAMEDBUFFERDATAPROC          glNamedBufferData;
	PFNGLNAMEDBUFFERSUBDATAPROC       glNamedBufferSubData;
	PFNGLGETNAMEDBUFFERSUBDATAPROC    glGetNamedBufferSubData;
	PFNGLBINDVERTEXARRAYPROC          glBindVertexArray;
	PFNGLGENVERTEXARRAYSPROC          glGenVertexArrays;
	PFNGLDELETEVERTEXARRAYSPROC       glDeleteVertexArrays;
	PFNGLENABLEVERTEXATTRIBARRAYPROC  glEnableVertexAttribArray;
	PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
	PFNGLVERTEXATTRIBPOINTERPROC      glVertexAttribPointer;
	PFNGLVERTEXATTRIBIPOINTERPROC     glVertexAttribIPointer;
	PFNGLVERTEXATTRIBLPOINTERPROC     glVertexAttribLPointer;
	PFNGLVERTEXATTRIBDIVISORPROC      glVertexAttribDivisor;
	PFNGLPRIMITIVERESTARTINDEXPROC    glPrimitiveRestartIndex;
	PFNGLTEXTURESTORAGE2DPROC glTexStorage2D;
	PFNGLGENERATEMIPMAPPROC   glGenerateMipmap;
	PFNGLGENFRAMEBUFFERSPROC    glGenFramebuffers;
	PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
	PFNGLBINDFRAMEBUFFERPROC    glBindFramebuffer;
	PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
	PFNGLGENRENDERBUFFERSPROC    glGenRenderbuffers;
	PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
	PFNGLBINDRENDERBUFFERPROC    glBindRenderbuffer;
	PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
	PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
	PFNGLUSEPROGRAMPROC         glUseProgram;
	PFNGLCREATESHADERPROC       glCreateShader;
	PFNGLDELETESHADERPROC       glDeleteShader;
	PFNGLCREATEPROGRAMPROC      glCreateProgram;
	PFNGLDELETEPROGRAMPROC      glDeleteProgram;
	PFNGLATTACHSHADERPROC       glAttachShader;
	PFNGLDETACHSHADERPROC       glDetachShader;
	PFNGLGETSHADERIVPROC        glGetShaderiv;
	PFNGLGETPROGRAMIVPROC       glGetProgramiv;
	PFNGLSHADERSOURCEPROC       glShaderSource;
	PFNGLCOMPILESHADERPROC      glCompileShader;
	PFNGLGETSHADERINFOLOGPROC   glGetShaderInfoLog;
	PFNGLGETPROGRAMINFOLOGPROC  glGetProgramInfoLog;
	PFNGLLINKPROGRAMPROC        glLinkProgram;
	PFNGLSHADERBINARYPROC       glShaderBinary;
	PFNGLGETPROGRAMBINARYPROC   glGetProgramBinary;
	PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
	PFNGLUNIFORM1FPROC          glUniform1f;
	PFNGLUNIFORM2FPROC          glUniform2f;
	PFNGLUNIFORM2FVPROC         glUniform2fv;
	PFNGLUNIFORM3FPROC          glUniform3f;
	PFNGLUNIFORM3FVPROC         glUniform3fv;
	PFNGLUNIFORM4FPROC          glUniform4f;
	PFNGLUNIFORM4FVPROC         glUniform4fv;
	PFNGLUNIFORM1IPROC          glUniform1i;
	PFNGLUNIFORMMATRIX3FVPROC   glUniformMatrix3fv;
	PFNGLUNIFORMMATRIX4FVPROC   glUniformMatrix4fv;
	PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
	PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
	PFNGLBINDFRAMEBUFFERPROC glBindFrameBuffer;
	PFNGLGETFRAMEBUFFERPARAMETERIVPROC glGetFramebufferParameteriv;
	PFNGLBEGINQUERYPROC    glBeginQuery;
	PFNGLENDQUERYPROC      glEndQuery;
	PFNGLCREATEQUERIESPROC glCreateQueries;
	PFNGLGENQUERIESPROC    glGenQueries;
	PFNGLDELETEQUERIESPROC glDeleteQueries;
	PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback;

	void initOpenGLfuncs();
};

} // namespace wwidget
