#pragma once

#include "../Widget.hpp"

#include <iostream>
#include <memory>

namespace widget {

/// Create a widget showing a dump of the widget's structure
std::unique_ptr<Widget> CreateDump(Widget* widget);
/// Adds CreateDump to another widget or, if one already exists, updates it.
Widget* ShowDump (Widget* showIn, Widget* dumpOf = nullptr);
/// Removes childs generated by the ShowDump and CreateDump functions
bool    RemoveDump(Widget* from);
/// Prints a dump of the widget's structure to a stream
void    PrintDump(std::ostream& to, Widget* dumpOf);

} // namespace widget
